### ISSUE TITLE
Replace ndt5 with ndt7

### ISSUE THREAD

**Issue by bassosimone** [m-lab/mlab-speedtest#10]
This task is about allowing users to choose ndt7 as an opt-in option. We should use [the reference JavaScript client](https://github.com/m-lab/ndt7-client-javascript).

@critzo has agreed to help @bassosimone move this forward. This issue exist as a tracking rerefence for one or more future PRs aimed at making this possible.

**Comment by bassosimone** [comment]
I'm removing myself from here and re-adding review/triage as I'm the bottleneck here.

**Comment by bassosimone** [comment]
Ah, I cannot add review/triage. Well, I guess this is not necessarily required?

**Comment by critzo** [comment]
@bassosimone If `ndt-server` emits a summary message as described in https://github.com/m-lab/ndt-server/issues/194 then it should be trivial to use that message in the ndt7 JS client front-end.  

For this integration, the task in my opinion will be simply replacing the current JS client with ndt7-client-javascript, and on the UI side using the summary message from ndt-server

**Comment by critzo** [comment]
This is now possible with https://github.com/m-lab/ndt7-js/ - the client will replace ndt5 not provide a second option.

**Comment by bassosimone** [comment]
Thanks @critzo, I'm very happy to know this is moving forward!

**Comment by critzo** [comment]
Completed with latest release.
