### ISSUE TITLE
user reports this site directs users to VIE01, a decommissioned site

### ISSUE THREAD

**Issue by critzo** [m-lab/mlab-speedtest#24]
It has been reported that this site still directs users in Austria to the site vie01, which was decommissioned in August 2020.

* [ ] check the version of Locate service in use
* [ ] update to the latest version
* [ ] update the NDT client to ndt7-js

**Comment by nkinkade** [comment]
@critzo: The datastore entities for vie01 were still in mlab-ns, and with a IPv4 status of "online". :( I removed all of them from production and staging. I believe that should clear up the issue. The expectation would be that a site that doesn't exist should be flagged as down and no traffic go there, despite it still existing in the datastore.  What I think happened here was that the site was removed in a way such that mlab-ns stopped updating status for the site before the entities were marked as being down, essentially leaving orphaned records in an "online" state that never got updated again. We'll need to figure out how to prevent this in the future.
