### ISSUE TITLE
Language-specific routes do not work due to their respective HTML files being out of date

### ISSUE THREAD

**Issue by RA80533** [m-lab/mlab-speedtest#35]
Two recent changes were made to the base index.html file that were never applied to the language-specific variants of the base (e.g., [/app/ru/index.html](https://github.com/m-lab/mlab-speedtest/blob/4cb40a00cc59ad46f8c7c1912461614c2bdc40a7/app/ru/index.html)):

1. 825d24a removed mlabService.js (see #25)  
    Requesting the non-existent script results in an HTTP status code 404
2. d892d28 added the ng-device-detector module (see #28)  
    The script containing the module is never imported, causing the application to terminate with an exception

Visit any of the live routes corresponding to the affected pages for a demonstration of the aforementioned issues.

Related #34

**Comment by robertodauria** [comment]
Hi @RA80533, thank you for reporting this! We released a fix that closed this issue together with https://github.com/m-lab/mlab-speedtest/issues/39 and https://github.com/m-lab/mlab-speedtest/issues/38.

**Comment by RA80533** [comment]
@robertodauria It appears that several strings aren't translated on some of the pages—not due to the pages themselves being out of date but rather the translations themselves. Should I go ahead and open an issue detailing further information?

The root of the issue seems to be that the translation files are out of date compared to the template file.

**Comment by robertodauria** [comment]
Ah, you are right. That particular string that was added recently was not made translatable. An issue and/or PR for the missing translations would be welcome.
